name: Run C++

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile
        run: g++ -std=c++17 main.cpp -o main
        
      - name: Run
        run: ./main
